/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/*
 * ImageSubmitter.java
 *
 * Created on Mar 16, 2011, 3:12:42 PM
 */

package ipclient;

import ipcommon.ImageProcessTemplate;
import java.io.DataOutputStream;
import java.io.File;
import java.io.FileInputStream;
import java.io.FileNotFoundException;
import java.io.FileOutputStream;
import java.io.IOException;
import java.rmi.NotBoundException;
import java.rmi.RemoteException;
import java.rmi.registry.LocateRegistry;
import java.rmi.registry.Registry;
import org.jdesktop.application.Action;

/**
 *
 * @author erts
 */
public class ImageSubmitter extends javax.swing.JFrame {

    /** Creates new form ImageSubmitter */
    public ImageSubmitter() {
        initComponents();
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jTextField1 = new javax.swing.JTextField();
        jButton1 = new javax.swing.JButton();
        jCheckBox1 = new javax.swing.JCheckBox();
        jCheckBox2 = new javax.swing.JCheckBox();
        jCheckBox3 = new javax.swing.JCheckBox();
        jTextField2 = new javax.swing.JTextField();
        jCheckBox4 = new javax.swing.JCheckBox();
        jLabel1 = new javax.swing.JLabel();
        jCheckBox5 = new javax.swing.JCheckBox();
        jTextField3 = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jTextField1.setText("I:\\color.png");
        jTextField1.setName("jTextField1"); // NOI18N

        javax.swing.ActionMap actionMap = org.jdesktop.application.Application.getInstance().getContext().getActionMap(ImageSubmitter.class, this);
        jButton1.setAction(actionMap.get("callRMI")); // NOI18N
        jButton1.setText("Process");
        jButton1.setName("jButton1"); // NOI18N

        jCheckBox1.setText("Grayscale");
        jCheckBox1.setName("jCheckBox1"); // NOI18N

        jCheckBox2.setText("Edge Detect");
        jCheckBox2.setName("jCheckBox2"); // NOI18N

        jCheckBox3.setText("Invert Color");
        jCheckBox3.setName("jCheckBox3"); // NOI18N

        jTextField2.setText("0.0");
        jTextField2.setName("jTextField2"); // NOI18N

        jCheckBox4.setText("Threshhold");
        jCheckBox4.setName("jCheckBox4"); // NOI18N

        jLabel1.setText("0 - 1");
        jLabel1.setName("jLabel1"); // NOI18N

        jCheckBox5.setText("Histogram Brighten");
        jCheckBox5.setName("jCheckBox5"); // NOI18N

        jTextField3.setText("i:\\final-color.png");
        jTextField3.setName("jTextField3"); // NOI18N

        jLabel2.setText("The processed image : ");
        jLabel2.setName("jLabel2"); // NOI18N

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(30, 30, 30)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jCheckBox5)
                    .addComponent(jCheckBox3)
                    .addComponent(jCheckBox2)
                    .addComponent(jCheckBox1)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, 255, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jButton1, javax.swing.GroupLayout.DEFAULT_SIZE, 95, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jCheckBox4)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jTextField2, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jLabel1))
                    .addComponent(jTextField3, javax.swing.GroupLayout.PREFERRED_SIZE, 314, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 193, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jCheckBox1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jCheckBox2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jCheckBox3)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jCheckBox4)
                    .addComponent(jTextField2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel1))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jCheckBox5)
                .addGap(63, 63, 63)
                .addComponent(jLabel2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jTextField3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(21, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
    * @param args the command line arguments
    */
    public static void main(String args[]) {
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new ImageSubmitter().setVisible(true);
            }
        });
    }

    @Action
    public void callRMI() throws RemoteException, NotBoundException, FileNotFoundException, IOException {
         String name = "Accounts";
         if (System.getSecurityManager() == null) {
           // System.setSecurityManager(new SecurityManager());
         }
        Registry registry = LocateRegistry.getRegistry(1099);
        //Registry registry = LocateRegistry.createRegistry("127.0.0.1",1099);
        //registry.list();
        ImageProcessTemplate hr = (ImageProcessTemplate) registry.lookup(name);

        hr.setImageName(new File(this.jTextField1.getText()).getName());
        hr.setImageContent(ImagePacket.readFileAsString(this.jTextField1.getText()));
       

        if(this.jCheckBox1.isSelected())
        {
            hr.setGray(true);
        }
        
         if(this.jCheckBox2.isSelected())
        {
             hr.setEdgeDetect(true);
        }

        
         if(this.jCheckBox3.isSelected())
        {
            hr.setInvertColor(true);
        }
        
         if(this.jCheckBox4.isSelected())
        {
             hr.setThreshold(Float.parseFloat(this.jTextField2.getText()));
        }

         if(this.jCheckBox5.isSelected())
        {
             hr.setHistogramBrighten(true);
        }

        byte[] finalImage = hr.getProcessedImage();

         try {


          FileOutputStream fos;

          DataOutputStream dos;

          File file= new File(this.jTextField3.getText());
          fos = new FileOutputStream(file);
          dos=new DataOutputStream(fos);
          dos.write(finalImage);
          dos.close();
          fos.close();





        } catch (IOException e) {
          e.printStackTrace();
        }

         
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JCheckBox jCheckBox1;
    private javax.swing.JCheckBox jCheckBox2;
    private javax.swing.JCheckBox jCheckBox3;
    private javax.swing.JCheckBox jCheckBox4;
    private javax.swing.JCheckBox jCheckBox5;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JTextField jTextField1;
    private javax.swing.JTextField jTextField2;
    private javax.swing.JTextField jTextField3;
    // End of variables declaration//GEN-END:variables

}
